#pragma once

#define CHARGE_CONTINUITY_CH1 A5
#define CHARGE_CONTINUITY_CH2 A4
#define CHARGE_CONTINUITY_CH3 A3
#define CHARGE_CONTINUITY_CH4 A2
#define CHARGE_DIVIDER_RATIO_MULTIPLIER (100.0+33.0)/(33.0)

#define CHARGE_DETONATE_CH1 30 
#define CHARGE_DETONATE_CH2 4
#define CHARGE_DETONATE_CH3 12
#define CHARGE_DETONATE_CH4 6

#define WIRE_CUT_SENSE A1
#define PUSHBUTTON 31

#define LED1_STATUS 9
#define LED2_ARMED 10
#define BUZZER 8

#define FLASH_CHIP_SS 17
#define FLASH_CHIP_WP 11

#define ACCELEROMETER_ADDRESS 0b0011000 
#define ACCELEROMETER_INT1 0
#define ACCELEROMETER_INT2 1

#define BAROMETER_ADDRESS 0b1110111


